services:
  stock-cafe:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
      - ../data:/app/data  # 👈 mount the data directory explicitly


